### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by alexbelgium** [alexbelgium/hassio-addons#75]
- [ ] Nextcloud add comma separated languages
- [ ] All : add 00-.sh script
- [ ] Resilio-sync config location issue
